apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqldb
  labels:
    app: sqldb
spec:
  selector:
    matchLabels:
      app: sqldb
  replicas: 1
  template:
    metadata:
      labels:
        app: sqldb
    spec:
      containers:
        - name: sqldb-container
          image: 311124730702.dkr.ecr.us-east-1.amazonaws.com/mysql-repo:4fc9c51
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: timhortons
            - name: MYSQL_DATABASE
              value: employees
          ports:
            - containerPort: 3306
              protocol: TCP
      imagePullSecrets:
        - name: secret-registry