apiVersion: v1
kind: Service
metadata:
  name: employee
  labels:
    app: employee
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
  selector:
    app: employee